# Generated by Django 5.2.1 on 2025-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.FloatField(default=0)),
                ('stock', models.PositiveIntegerField(default=0, help_text='库存数量')),
                ('reserved', models.PositiveIntegerField(default=0, help_text='已预订数量')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='good_name_idx')],
            },
        ),
    ]
